module.exports = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  ACCOUNT_ALREADY_VERIFIED: 'ACCOUNT_ALREADY_VERIFIED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // Rides
  RIDE_NOT_FOUND: 'RIDE_NOT_FOUND',
  RIDE_CLOSED: 'RIDE_CLOSED',
  RIDE_NOT_OPEN: 'RIDE_NOT_OPEN',
  NOT_RIDE_OWNER: 'NOT_RIDE_OWNER',

  // Requests
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  REQUEST_NOT_PENDING: 'REQUEST_NOT_PENDING',
  CANNOT_REQUEST_OWN_RIDE: 'CANNOT_REQUEST_OWN_RIDE',
  NO_SEATS_AVAILABLE: 'NO_SEATS_AVAILABLE',

  // Messages
  NOT_RIDE_PARTICIPANT: 'NOT_RIDE_PARTICIPANT',

  // Ratings
  RATING_NOT_FOUND: 'RATING_NOT_FOUND',
  DUPLICATE_RATING: 'DUPLICATE_RATING',
  RIDE_NOT_COMPLETED: 'RIDE_NOT_COMPLETED',
  CANNOT_RATE_SELF: 'CANNOT_RATE_SELF',
  NOT_RIDE_PARTICIPANT_RATING: 'NOT_RIDE_PARTICIPANT_RATING',
};
